/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("pl.mija.gcp.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":gpc-utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("pl.mija.gcp.app.AppKt")
}
